interface ReportHeaderProps {
  title: string
  subtitle?: string
  dateRange?: string
  generatedAt?: string
  generatedBy?: string
  filters?: string[]
}

export function ReportHeader({
  title,
  subtitle,
  dateRange,
  generatedAt,
  generatedBy,
  filters,
}: ReportHeaderProps) {
  const meta = [
    dateRange != null ? { label: 'Report period', value: dateRange } : null,
    generatedAt != null ? { label: 'Generated', value: generatedAt } : null,
    generatedBy != null ? { label: 'Generated by', value: generatedBy } : null,
  ].filter((entry) => entry != null)

  return (
    <header className="report-header">
      <div className="report-header__brandrow">
        <img src="/logo.png" alt="" className="report-header__logo" />
        <div>
          <p className="report-header__platform">PALITPADDLEBAI MART</p>
          <p className="report-header__subtitle">{subtitle ?? 'Admin Report'}</p>
        </div>
      </div>
      <h1 className="report-header__title">{title}</h1>
      {meta.length > 0 ? (
        <dl className="report-header__meta">
          {meta.map((entry) => (
            <div key={entry!.label} className="report-header__meta-item">
              <dt>{entry!.label}</dt>
              <dd>{entry!.value}</dd>
            </div>
          ))}
        </dl>
      ) : null}
      {filters != null && filters.length > 0 ? (
        <p className="report-header__filters">
          Applied filters: {filters.join(' · ')}
        </p>
      ) : null}
    </header>
  )
}